server:
  port: 8088
  servlet:
    session:
      cookie:
        same-site: "none"
      timeout: 900s
    tomcat:
      uri-encoding: UTF-8
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/user?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
      username: root
      password: 123456a



#Debug: true